language: cpp
os: linux
dist: xenial

compiler:
  - g++

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git-core
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq g++ gcc
  - sudo apt-get install -qq lcov ggcov
  - sudo apt-get install libboost-all-dev

before_script:
  - cmake -H. -B_builds

script:
  - cmake --build _builds
  - cd _builds
  - ctest
