language: cpp

os: linux
dist: xenial
sudo: required

compiler:
  - g++

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++17
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

before_script:
  - g++ --version
  - gcc --version
  - cmake --version

script:
  - cmake -H. -B_builds
  - cmake --build _builds
  - cd _builds
  - ctest


