language: cpp

dist: xenial

compiler:
  - g++

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential cmake git-core lcov ggcov g++
  - sudo apt-get install libboost-all-dev

before_script:
  - cmake -H. -B_builds

script:
  - cmake --build _builds
  - cd _builbs
  - ctest
